version: 2.0
jobs:
  deploy:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - run:
          name: Deploy using SSH
          command: |
            ssh ivan@ereshchenko.com -oStrictHostKeyChecking=no "cd Documents/AnimeSOC/botchyan; git stash; git pull; ./.circleci/tmux.sh"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy